Mistake
Isroiljon5355/team pull request #18
Opened 2023-03-24 08:32 UTC by xakimovotabek200

2023-03-24 08:39 UTC, tolibjon1015 approved these changes

2023-03-24 08:39 UTC, Ahmadullo21 approved these changes

2023-03-24 08:41 UTC, tolibjon1015 submitted a review, later dismissed

2023-03-24 08:41 UTC, tolibjon1015 commented on src/components/Cards/Card.jsx
> +    </div>
responsive to'g'irlang

2023-03-24 08:47 UTC, ibrohim5009 requested changes

2023-03-24 08:47 UTC, ibrohim5009 commented on src/components/Cards/Card.css
> +}
nimaga css tailwend emas ?????????????????????????????

2023-03-24 08:49 UTC, akbarali0705 requested changes

2023-03-24 08:49 UTC, akbarali0705 commented on src/components/Cards/Card.css
> +}
Css nima qilyapti?

2023-03-24 08:49 UTC, akbarali0705 commented on src/style.css
> +}
Css?

2023-03-24 08:51 UTC, Ahmadullo21 requested changes

2023-03-24 08:51 UTC, Ahmadullo21 commented on src/components/Cards/Card.jsx
> +    </div>
responsive to'g'irlang

2023-03-26 12:03 UTC, ibrohim5009 requested changes

2023-03-26 12:03 UTC, ibrohim5009 commented on src/components/Cards/Card.css
> +}
nimaga css?

2023-03-26 12:38 UTC, samandar0806 approved these changes

2023-03-26 12:38 UTC, samandar0806 commented on src/components/Cards/Card.jsx
> +    },
![React App - Google Chrome 3_24_2023 7_33_28 AM](https://user-images.githubusercontent.com/125674961/227776133-b625774c-617f-4eeb-a35f-53871877e36e.png)

nimaga (love) button hoverda ozgarib ketyapti

2023-03-26 17:23 UTC, ibrohim5009 approved these changes

2023-03-26 18:35 UTC, akbarali0705 requested changes

2023-03-26 18:35 UTC, akbarali0705 commented on src/data.js
> +];
![image](https://user-images.githubusercontent.com/124563238/227796703-e222a5e5-3a75-4e2c-94b7-659e8631a34f.png)
look at responsive

2023-03-26 18:36 UTC, akbarali0705 approved these changes

2023-03-27 09:55 UTC, ibrohim5009 submitted a review, later dismissed
media ???

2023-03-27 18:25 UTC, tolibjon1015 requested changes

2023-04-02 08:12 UTC, akbarali0705 approved these changes

2023-04-02 08:13 UTC, akbarali0705 approved these changes

2023-04-02 15:41 UTC, tolibjon1015 requested changes, later dismissed

2023-04-02 15:41 UTC, tolibjon1015 commented on src/components/Cards/Card.css
> +}
![image](https://user-images.githubusercontent.com/120715779/229363492-bf16c202-60e5-4f8e-b17e-287138af45ef.png)
orasidagi masofa juda katta va cardga hover bo'lganda sekin chiqib tez orqaga qaytib ketyapti !!!

2023-04-02 18:25 UTC, xakimovotabek200 commented on src/components/Cards/Card.css
> +}
sandayam shu muammmo

2023-04-03 08:45 UTC, Ahmadullo21 approved these changes

2023-04-03 08:48 UTC, ibrohim5009 commented
![image](https://user-images.githubusercontent.com/123284726/229459318-1cf4d132-816f-453d-bbab-5b819498416c.png)
media ???????????

2023-04-03 08:49 UTC, ibrohim5009 requested changes
src/assepts/PubgSectionImg/game-action.png

2023-04-03 08:49 UTC, ibrohim5009 approved these changes

2023-04-03 08:50 UTC, Ahmadullo21 approved these changes

2023-04-03 09:50 UTC, merged