add footer
Isroiljon5355/team pull request #19
Opened 2023-03-24 09:46 UTC by ibrohim5009

2023-03-24 09:46 UTC, ibrohim5009 commented
add footer

2023-03-24 10:27 UTC, Muhammadali2oo6 requested changes
yoqmadi very bad!!!!!

2023-03-24 17:25 UTC, ibrohim5009 commented
footer add

2023-03-25 10:09 UTC, tolibjon1015 requested changes

2023-03-25 10:09 UTC, tolibjon1015 commented on src/components/footer/Footer.jsx
> +          </h1>
span ga width berib rang bersang yaxshi bo'lar edi

2023-03-25 10:09 UTC, tolibjon1015 commented on src/components/footer/Footer.jsx
> +            />
![image](https://user-images.githubusercontent.com/120715779/227710832-f1726e78-d378-4be4-a720-159459ffd11e.png)
textni surib qo'y

2023-03-25 10:09 UTC, tolibjon1015 commented on src/components/footer/Footer.jsx
> +    </div>
![image](https://user-images.githubusercontent.com/120715779/227710872-ab46eab2-334d-4987-a75b-a2eee8c21cbd.png)
bir tekkisda emas

2023-03-25 12:42 UTC, ibrohim5009 commented on src/components/footer/Footer.jsx
> +          </h1>
bunga width beril maydi

2023-03-25 18:16 UTC, xakimovotabek200 requested changes

2023-03-25 18:16 UTC, xakimovotabek200 commented on src/components/footer/Footer.jsx
> +            <a className="text-[#fff] list-none leading-8 " href="#">
nima a?

2023-03-25 18:16 UTC, xakimovotabek200 commented on src/components/footer/Footer.jsx
> +            My service is not something I even think about because <br /> it is
cursor-pointer bolishi kerak edi?

2023-03-25 18:16 UTC, xakimovotabek200 commented on src/components/footer/Footer.jsx
> +            <FaFacebookF className="bg-gradient-to-r from-purple-500 to-pink-500 w-[30px] h-[30px] rounded-[50%] p-[7px]" />
hover

2023-03-26 05:46 UTC, samandar0806 approved these changes

2023-03-26 05:48 UTC, samandar0806 approved these changes
ozgartir

2023-03-27 08:42 UTC, akbarali0705 requested changes

2023-03-27 08:42 UTC, akbarali0705 commented on src/components/footer/Footer.jsx
> +            alt=""
cursor pointer emasmi

2023-03-27 09:48 UTC, xakimovotabek200 requested changes

2023-03-27 09:48 UTC, xakimovotabek200 commented on src/components/footer/Footer.jsx
> +          <h1 className="text-[#fff]">
media

2023-03-27 09:49 UTC, tolibjon1015 requested changes

2023-03-27 09:49 UTC, tolibjon1015 commented on src/components/footer/Footer.jsx
> +            />
![image](https://user-images.githubusercontent.com/120715779/227906534-02821f1a-afc3-42ce-8e81-0335deb9d179.png)
mediani to'g'irla

2023-03-27 09:53 UTC, ibrohim5009 commented on src/components/footer/Footer.jsx
> +            My service is not something I even think about because <br /> it is
buldi

2023-03-27 09:57 UTC, samandar0806 approved these changes

2023-03-27 09:57 UTC, samandar0806 commented on src/components/footer/Footer.jsx
> +        <p className=" text-[#fff] pl-[420px] mt-2 cursor-pointer">
padding left kop emasmi

2023-03-27 09:59 UTC, samandar0806 requested changes

2023-03-27 09:59 UTC, samandar0806 commented on src/components/footer/footer.css
> +  padding-right: 80px;
qoida boyicha padding left 10px dan otib ketsa padding ni ozini ishlatish kerak

2023-04-03 10:59 UTC, Ahmadullo21 approved these changes

2023-04-03 10:59 UTC, xakimovotabek200 approved these changes

2023-04-03 10:59 UTC, akbarali0705 requested changes

2023-04-03 10:59 UTC, akbarali0705 commented on src/components/footer/footer.css
> +}
nimaga css

2023-04-03 10:59 UTC, akbarali0705 commented on src/components/footer/LinkServives.jsx
> +    <div className="mt-5">
divga nimaga mt bergansan?

2023-04-03 10:59 UTC, akbarali0705 approved these changes

2023-04-03 11:00 UTC, Muhammadali2oo6 approved these changes
good job

2023-04-03 11:02 UTC, akbarali0705 requested changes

2023-04-03 11:02 UTC, akbarali0705 commented on src/components/footer/Link.jsx
> +            </h4>
nimaga h4?

2023-04-03 11:03 UTC, Muhammadali2oo6 approved these changes

2023-04-03 11:04 UTC, merged