medium
Isroiljon5355/team pull request #21
Opened 2023-03-27 17:59 UTC by Muhammadali2oo6

2023-03-27 18:22 UTC, tolibjon1015 requested changes

2023-03-27 18:22 UTC, tolibjon1015 commented on src/medium/Medium.jsx
> +export default Section;
![image](https://user-images.githubusercontent.com/120715779/228031433-2e4ffc7a-9f81-4f8d-b2fc-007ece664f25.png)
mediasini to'g'irlang juda yomon holatga kelib qolibdi . Prettier ni ham ishlatib oling

2023-03-27 18:22 UTC, tolibjon1015 commented on src/medium/Medium.jsx
> +              <div className="w-[15%] h-[160px] absolute top-[67%] mx-[30px] backdrop-blur-[33px] p-[20px] rounded-lg text-white bg-[rgba(0,0,0,.6)]">
width height berib ishlamang mediasiga kelganda bittadan to'g'irlab chiqishga to'g'ri keladi

2023-03-28 14:25 UTC, xakimovotabek200 requested changes

2023-03-28 14:25 UTC, xakimovotabek200 commented on src/medium/Medium.jsx
> +                <div className="w-[120px] py-[10px] border-none overflow-hidden rounded-lg  bg-gradient-to-r from-red-600 to-indigo-500 hover:bg-gradient-to-l to-indigo-500 from-red-600 text-white">
mashi joyini pulga olarmidingiz?

2023-03-31 08:56 UTC, ibrohim5009 requested changes

2023-03-31 08:56 UTC, ibrohim5009 commented on src/medium/Medium.jsx
> +            </div>
prettini togrlang???????????????????

2023-03-31 08:58 UTC, ibrohim5009 commented
![Uploading image.png…]()
nima bu?????????????????????????

2023-03-31 09:01 UTC, ibrohim5009 requested changes
![image](https://user-images.githubusercontent.com/123284726/229076009-430cbfbc-fd1a-465f-8d9a-98de84f54c54.png)

2023-03-31 09:01 UTC, ibrohim5009 commented on src/medium/Medium.jsx
> +                    <button>Order Now</button>
prettirda xato

2023-04-03 09:22 UTC, xakimovotabek200 requested changes

2023-04-03 09:22 UTC, xakimovotabek200 commented on src/medium/Medium.jsx
> +                <div className="flex">
responsive no

2023-04-03 10:56 UTC, closed without merging